//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWedding.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Wedding {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Wedding() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyWedding.Resources.Wedding", typeof(Wedding).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tillgängliga.
        /// </summary>
        public static string available {
            get {
                return ResourceManager.GetString("available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tillbaka.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakta oss.
        /// </summary>
        public static string contact_contactus {
            get {
                return ResourceManager.GetString("contact_contactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ditt namn.
        /// </summary>
        public static string contact_yourname {
            get {
                return ResourceManager.GetString("contact_yourname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicera meddelandet.
        /// </summary>
        public static string guestbook_btn {
            get {
                return ResourceManager.GetString("guestbook_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel uppstod i kommunikation med tjänst för gästboken.
        /// </summary>
        public static string guestbook_errormsg {
            get {
                return ResourceManager.GetString("guestbook_errormsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minst två tecken.
        /// </summary>
        public static string guestbook_minimumtxt {
            get {
                return ResourceManager.GetString("guestbook_minimumtxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett meddelande behöver anges.
        /// </summary>
        public static string guestbook_msg {
            get {
                return ResourceManager.GetString("guestbook_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minst två tecken i meddelandet.
        /// </summary>
        public static string guestbook_msg_min {
            get {
                return ResourceManager.GetString("guestbook_msg_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sjövillan, där festen äger rum..
        /// </summary>
        public static string guestbook_villa {
            get {
                return ResourceManager.GetString("guestbook_villa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gästbok.
        /// </summary>
        public static string guestbooktitle {
            get {
                return ResourceManager.GetString("guestbooktitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14 maj 2016 i Nacka kyrka kl. 15.00.
        /// </summary>
        public static string index_date {
            get {
                return ResourceManager.GetString("index_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dagar.
        /// </summary>
        public static string index_days {
            get {
                return ResourceManager.GetString("index_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu är vi äntligen gifta!.
        /// </summary>
        public static string index_h1_title {
            get {
                return ResourceManager.GetString("index_h1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timmar.
        /// </summary>
        public static string index_hours {
            get {
                return ResourceManager.GetString("index_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stort tack till er alla som gjorde vår bröllopsdag helt fantastisk! Tack också för Eevis underbara sång med vackert pianospel av Päivi och för alla jättefina presenter!.
        /// </summary>
        public static string index_info {
            get {
                return ResourceManager.GetString("index_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuter.
        /// </summary>
        public static string index_minutes {
            get {
                return ResourceManager.GetString("index_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidan kommer inom kort att uppdateras med bilder!.
        /// </summary>
        public static string index_pageupdate {
            get {
                return ResourceManager.GetString("index_pageupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotoalbum.
        /// </summary>
        public static string index_photoalbum {
            get {
                return ResourceManager.GetString("index_photoalbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Här är ett urval av bilder från våra år tillsammans..
        /// </summary>
        public static string index_photoinfo {
            get {
                return ResourceManager.GetString("index_photoinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekunder.
        /// </summary>
        public static string index_seconds {
            get {
                return ResourceManager.GetString("index_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reza och Pompi, tack för att ni fotograferade och filmade!.
        /// </summary>
        public static string index_ThanksPictures {
            get {
                return ResourceManager.GetString("index_ThanksPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bröllop.
        /// </summary>
        public static string index_viewbag_title {
            get {
                return ResourceManager.GetString("index_viewbag_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klädsel: Kavaj. Innebär för honom ljus eller mörk kostym och för henne klänning, kjol eller finbyxor..
        /// </summary>
        public static string info_clothes {
            get {
                return ResourceManager.GetString("info_clothes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Färgtema på bröllopet är lavendel, aprikos och grått..
        /// </summary>
        public static string info_colortheme {
            get {
                return ResourceManager.GetString("info_colortheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vägbeskrivning, från Nacka Kyrka till Sjövillan.
        /// </summary>
        public static string info_direction {
            get {
                return ResourceManager.GetString("info_direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viktig information.
        /// </summary>
        public static string info_importantinfo {
            get {
                return ResourceManager.GetString("info_importantinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sjövillan.
        /// </summary>
        public static string info_link {
            get {
                return ResourceManager.GetString("info_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berätta gärna om eventuella allergier eller annat som vi behöver veta. Det gör du enklast via menyn &quot;Kontakta oss&quot;..
        /// </summary>
        public static string info_msg {
            get {
                return ResourceManager.GetString("info_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gärna såpbubblor på bröllopet, istället för riskastande. 24 stycken små flaskor kommer att delas ut..
        /// </summary>
        public static string info_msg2 {
            get {
                return ResourceManager.GetString("info_msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.S.A. senast 7 april. Det går bra att svara på inbjudan till bröllopet här på hemsidan eller via telefon eller mail..
        /// </summary>
        public static string info_osa {
            get {
                return ResourceManager.GetString("info_osa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Festen kommer att äga rum på Sjövillan i Lilla Nyckelviken, som ligger 5 km från kyrkan. Läs mer om den på följande länk:.
        /// </summary>
        public static string info_partyinfo {
            get {
                return ResourceManager.GetString("info_partyinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planerar du att hålla ett tal? Meddela i så fall Torgils Hjalmarson (torgils.hjalmarson@gmail.com), toast master..
        /// </summary>
        public static string info_toastmaster {
            get {
                return ResourceManager.GetString("info_toastmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vid frågor om webbsidan, kontakta Henrik Hjalmarsson (webbansvarig).
        /// </summary>
        public static string layout_ask {
            get {
                return ResourceManager.GetString("layout_ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string layout_menu1 {
            get {
                return ResourceManager.GetString("layout_menu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önskelista.
        /// </summary>
        public static string layout_menu2 {
            get {
                return ResourceManager.GetString("layout_menu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viktig information.
        /// </summary>
        public static string layout_menu3 {
            get {
                return ResourceManager.GetString("layout_menu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakta oss.
        /// </summary>
        public static string layout_menu4 {
            get {
                return ResourceManager.GetString("layout_menu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gästbok.
        /// </summary>
        public static string layout_menu5 {
            get {
                return ResourceManager.GetString("layout_menu5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök.
        /// </summary>
        public static string layout_search {
            get {
                return ResourceManager.GetString("layout_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Söksträng.
        /// </summary>
        public static string layout_searchstring {
            get {
                return ResourceManager.GetString("layout_searchstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julia och Henriks bröllop.
        /// </summary>
        public static string layout_wedding {
            get {
                return ResourceManager.GetString("layout_wedding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bröllop.
        /// </summary>
        public static string layout_wedding_short {
            get {
                return ResourceManager.GetString("layout_wedding_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Länk.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Länk saknas.
        /// </summary>
        public static string linkmissing {
            get {
                return ResourceManager.GetString("linkmissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logga In.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösenord.
        /// </summary>
        public static string login_password {
            get {
                return ResourceManager.GetString("login_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inloggningsnamn.
        /// </summary>
        public static string login_userid {
            get {
                return ResourceManager.GetString("login_userid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ditt meddelande.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange ett meddelande.
        /// </summary>
        public static string messagemandatory {
            get {
                return ResourceManager.GetString("messagemandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Här kan du lämna meddelanden till Julia och/eller Henrik, t.ex. om eventuella allergier, OSA eller om du bara vill lämna en hälsning..
        /// </summary>
        public static string messages_info {
            get {
                return ResourceManager.GetString("messages_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil.
        /// </summary>
        public static string mobile {
            get {
                return ResourceManager.GetString("mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namn.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namn är obligatoriskt.
        /// </summary>
        public static string namemandatory {
            get {
                return ResourceManager.GetString("namemandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to av.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösenord.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestman: Fredrik Hjalmarson.
        /// </summary>
        public static string program_bestman {
            get {
                return ResourceManager.GetString("program_bestman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brudtärna: Ly Kaljumets.
        /// </summary>
        public static string program_brudgirl {
            get {
                return ResourceManager.GetString("program_brudgirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nacka Kyrka, Gamla Värmdövägen 14.
        /// </summary>
        public static string program_churchadress {
            get {
                return ResourceManager.GetString("program_churchadress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dans och musik.
        /// </summary>
        public static string program_dance {
            get {
                return ResourceManager.GetString("program_dance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middag, havsbuffé.
        /// </summary>
        public static string program_dinner {
            get {
                return ResourceManager.GetString("program_dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information kommer.
        /// </summary>
        public static string program_info {
            get {
                return ResourceManager.GetString("program_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marskalk: Per-Åke Christiansson.
        /// </summary>
        public static string program_marsalk {
            get {
                return ResourceManager.GetString("program_marsalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bröllopsmasch: Wagners Bröllopsmarsch.
        /// </summary>
        public static string program_marscher {
            get {
                return ResourceManager.GetString("program_marscher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppfotografering utanför Sjövillan. Fotograf: Reza Zaker.
        /// </summary>
        public static string program_photo {
            get {
                return ResourceManager.GetString("program_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Präst: Gudni Agnarsson.
        /// </summary>
        public static string program_priest {
            get {
                return ResourceManager.GetString("program_priest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Välkomstskål.
        /// </summary>
        public static string program_toast {
            get {
                return ResourceManager.GetString("program_toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toastmaster: Torgils Hjalmarson.
        /// </summary>
        public static string program_toastmaster {
            get {
                return ResourceManager.GetString("program_toastmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport med abonnerad buss till Sjövillan i Lilla Nyckelviken.
        /// </summary>
        public static string program_transport {
            get {
                return ResourceManager.GetString("program_transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigsel i Nacka Kyrka.
        /// </summary>
        public static string program_vigsel {
            get {
                return ResourceManager.GetString("program_vigsel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösenord måste anges.
        /// </summary>
        public static string pwmandatory {
            get {
                return ResourceManager.GetString("pwmandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tinga.
        /// </summary>
        public static string Reserve {
            get {
                return ResourceManager.GetString("Reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skicka.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du intresserad av hur webbsidan är utvecklad, klicka på länken..
        /// </summary>
        public static string technicalinfo {
            get {
                return ResourceManager.GetString("technicalinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ångra.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önskelista.
        /// </summary>
        public static string wishlist {
            get {
                return ResourceManager.GetString("wishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../Content/images/wishlist/Lock2.png.
        /// </summary>
        public static string wishlist_filepathLock {
            get {
                return ResourceManager.GetString("wishlist_filepathLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../Content/images/wishlist/Unlock2.png.
        /// </summary>
        public static string wishlist_filepathUnlock {
            get {
                return ResourceManager.GetString("wishlist_filepathUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tycker du att någon av presenterna nedan verkar lämpliga? Tinga den i så fall, för att förhinda att flera personer köper samma. Ångrar du dig är det bara att klicka på &quot;Ångra-knappen&quot;. Eftersom inloggningen är anonym vet man inte vem som köpt vad..
        /// </summary>
        public static string wishlist_info {
            get {
                return ResourceManager.GetString("wishlist_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resebidrag.
        /// </summary>
        public static string wishlist_travelfund {
            get {
                return ResourceManager.GetString("wishlist_travelfund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bidrag till vår kommande bröllopsresa är välkommet! I så fall går det bra att swisha till Henriks mobilnummer (0046703053431), eller till SEB 5385 00 128 08.
        /// </summary>
        public static string wishlist_travelfund_text {
            get {
                return ResourceManager.GetString("wishlist_travelfund_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viner.
        /// </summary>
        public static string wishlist_wines {
            get {
                return ResourceManager.GetString("wishlist_wines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viner är alltid uppskattat! T.ex. rött, vitt eller mousserande. Vi föredrar torra viner..
        /// </summary>
        public static string wishlist_wines_text {
            get {
                return ResourceManager.GetString("wishlist_wines_text", resourceCulture);
            }
        }
    }
}
